# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/rfpye', 'doc_host': 'https://ronaldokun.github.io', 'git_url': '', 'lib_path': 'rfpye'},
  'syms': {'rfpye.blocks': {}, 'rfpye.constants': {}, 'rfpye.parser': {}, 'rfpye.utils': {}}}
