[build-system]
requires = ["setuptools>=51.1.2", "wheel", "Cython>=0.29.23,<3", "numpy>=1.20.3"]
build-backend = "setuptools.build_meta"

[project]
name = "rfpye"
version = "0.3.7"
description = "Binary Files Parser resulted from the script Logger from CRFS - Rfeye Node Equipament"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
authors = [{name = "Ronaldo Batista", email = "ronaldokun@gmail.com"}]
keywords = ["spectrum", "monitoring"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Natural Language :: Portuguese",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "Cython",
  "numpy",
  "fastcore",
  "feather-format",
  "pandas",
  "rich",
  "openpyxl",
  "loguru",
]

[project.optional-dependencies]
dev = [
  "nbdev>=2.3.0",
  "mypy",
  "black",
  "twine",
  "pytest",
]

[project.urls]
Documentation = "https://ronaldokun.github.io/rfpye"
Homepage = "https://github.com/ronaldokun/rfpye/tree/master/"
