[build-system]
requires = ["setuptools>=51.1.2", "wheel", "numpy>=1.20.3"]
build-backend = "setuptools.build_meta"

[project]
name = "rfpye"
version = "0.3.8"
description = "Binary Files Parser resulted from the script Logger from CRFS - Rfeye Node Equipament"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
authors = [{name = "Ronaldo Batista", email = "ronaldokun@gmail.com"}]
keywords = ["spectrum", "monitoring"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Natural Language :: Portuguese",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "Cython",
  "numpy",
  "fastcore",
  "pandas",
  "rich",
  "loguru",
]

[project.optional-dependencies]
dev = [
  "fasttransform",
  "mypy",
  "ruff",
  "twine",
  "pytest",
]

[project.urls]
Documentation = "https://ronaldokun.github.io/rfpye"
Homepage = "https://github.com/ronaldokun/rfpye/tree/master/"

[tool.nbdev]
lib_path = "rfpye"
nbs_path = "nbs"
doc_path = "docs"
recursive = true

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "nbdev>=3.0.0",

]
