# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parse_input": "00_main.ipynb",
         "get_files": "01_parser.ipynb",
         "path_type": "04_blocks.ipynb",
         "bin_val": "04_blocks.ipynb",
         "bytes_encoded": "04_blocks.ipynb",
         "datetime_object": "04_blocks.ipynb",
         "binary_file_generator": "02_utils.ipynb",
         "filtered_binary_file_generator": "02_utils.ipynb",
         "group_generator": "02_utils.ipynb",
         "bin2dec": "02_utils.ipynb",
         "bin2str": "02_utils.ipynb",
         "bin2date": "02_utils.ipynb",
         "bin2time": "02_utils.ipynb",
         "decode_spectrum": "02_utils.ipynb",
         "decode_spectrum_bytes": "02_utils.ipynb",
         "BinFileStats": "04_blocks.ipynb",
         "Block": "04_blocks.ipynb",
         "TimedBlock": "04_blocks.ipynb",
         "DataType21": "04_blocks.ipynb",
         "DataType24": "04_blocks.ipynb",
         "DataType40": "04_blocks.ipynb",
         "DataType41": "04_blocks.ipynb",
         "DataType63": "04_blocks.ipynb",
         "DataType65": "04_blocks.ipynb",
         "Error": "04_blocks.ipynb",
         "InputFileError": "04_blocks.ipynb",
         "retorna_classe": "04_blocks.ipynb"}

modules = ["main.py",
           "parser.py",
           "utils.py",
           "tests.py",
           "blocks.py"]

doc_url = "https://ronaldokun.github.io/rfpy/"

git_url = "https://github.com/ronaldokun/rfpy/tree/master/"

def custom_doc_links(name): return None
