# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"process_bin": "00_main.ipynb",
         "path_type": "03_blocks.ipynb",
         "bin_val": "03_blocks.ipynb",
         "bytes_encoded": "03_blocks.ipynb",
         "datetime_object": "03_blocks.ipynb",
         "META": "01_parser.ipynb",
         "LEVELS": "01_parser.ipynb",
         "COLS_B": "01_parser.ipynb",
         "BLOCO_40": "01_parser.ipynb",
         "BLOCO_63": "01_parser.ipynb",
         "get_files": "01_parser.ipynb",
         "binary_file_generator": "01_parser.ipynb",
         "file2block": "01_parser.ipynb",
         "optimize_floats": "01_parser.ipynb",
         "optimize_ints": "01_parser.ipynb",
         "optimize_objects": "01_parser.ipynb",
         "optimize": "01_parser.ipynb",
         "export_bin_level": "01_parser.ipynb",
         "export_bin_meta": "01_parser.ipynb",
         "bin2dec": "02_utils.ipynb",
         "bin2str": "02_utils.ipynb",
         "bin2date": "02_utils.ipynb",
         "bin2time": "02_utils.ipynb",
         "decode_spectrum": "02_utils.ipynb",
         "decode_spectrum_bytes": "02_utils.ipynb",
         "create_base_block": "03_blocks.ipynb",
         "BASEBLOCK": "03_blocks.ipynb",
         "DICT_PROCESSING": "03_blocks.ipynb",
         "DICT_UNIT": "03_blocks.ipynb",
         "BaseBlock": "03_blocks.ipynb",
         "TimedBlock": "03_blocks.ipynb",
         "DType21": "03_blocks.ipynb",
         "DType24": "03_blocks.ipynb",
         "DType40": "03_blocks.ipynb",
         "DType41": "03_blocks.ipynb",
         "DType63": "03_blocks.ipynb",
         "DType65": "03_blocks.ipynb",
         "block_constructor": "03_blocks.ipynb",
         "TYPE_CLASS": "03_blocks.ipynb"}

modules = ["main.py",
           "parser.py",
           "utils.py",
           "blocks.py"]

doc_url = "https://ronaldokun.github.io/rfpy/"

git_url = "https://github.com/ronaldokun/rfpy/tree/master/"

def custom_doc_links(name): return None
